[package]
name = "halo2_efficient_ecdsa"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
#halo2_proofs = { git = "https://github.com/personaelabs/halo2-secp" }
#halo2_gadgets = { git = "https://github.com/personaelabs/halo2-secp" }

halo2_proofs = { git = "https://github.com/zcash/halo2.git" }
halo2_gadgets = { git = "https://github.com/zcash/halo2.git"}

num-bigint = { version = "0.4", features = ["rand"] }
ff = "0.12.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
getrandom = { version = "0.2", features = ["js"]}
wasm-bindgen = { version = "0.2.63", features = ["serde-serialize"]}
console_error_panic_hook = "0.1.7"
rayon = "1.5"
web-sys = { version = "0.3", features = ["Request", "Window", "Response", "console"] }
wasm-bindgen-futures = "0.4"
rand_core = { version = "0.6", default-features = false }
rand = "0.8"
js-sys = "0.3"
serde-wasm-bindgen = "0.4.5"
plotters = { version = "0.3.0", optional = true }
tabbycat = { version = "0.1", features = ["attributes"], optional = true }

lazy_static = "1"
pasta_curves = "0.4"

# more info in src/wasm.rs
[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen-rayon = { version = "1.0"}

[features]
dev-graph = ["halo2_proofs/dev-graph", "plotters"]

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
ark-std = { version = "0.3.0", features = ["print-trace"] }




